### ISSUE TITLE
Version type confusion

### ISSUE THREAD

**Issue by viraptor** [awsdocs/aws-codedeploy-user-guide#20]
In the documentation for [appspec structure](https://github.com/awsdocs/aws-codedeploy-user-guide/blob/master/doc_source/reference-appspec-file-structure.md#appspec-file-structure-for-amazon-ecs-deployments), the version field is described with:

> Specify version with a string.

This doesn't match every available example in the docs. In both YAML and JSON format, the version is defined as bare `0.0`, which is a float.

**Comment by elijahbatkoski** [comment]
Hey @viraptor , sorry for the delay here. I'm new to the AWS docs team and came across this issue. So, it looks to me like it's just a string that contains the number 0.0, is that not the case? Sorry if I'm misunderstanding!

**Comment by markiver** [comment]
Hello,

@elijahbatkoski is absolutely correct. The version number for an AppSpec file is 0.0 and is specified as a string in the AppSpec file. While the version must always be specified, it is not a setting you need to be concerned with because it's reserved for future use.

@viraptor, thank you for taking the time to submit your issue. It's customers like you who help us keep our documentation as current and useful as possible.

Kind regards,

Mark
