### ISSUE TITLE
AWS CodeDeploy Bitbucket app is deprecated

### ISSUE THREAD

**Issue by ZhukovAlexander** [awsdocs/aws-codedeploy-user-guide#23]
Bitbucket announced the deprecation of the CodeDeploy app in favor of the [aws-code-deploy pipe](https://bitbucket.org/product/features/pipelines/integrations?p=atlassian/aws-code-deploy) recently:
https://confluence.atlassian.com/bitbucket/end-of-support-announcement-2019-12-03-aws-codedeploy-app-removal-980460164.html.

However, this page https://github.com/awsdocs/aws-codedeploy-user-guide/blob/master/doc_source/application-revisions-repository-type.md still links to the blog post with the deprecated CodeDeploy integration, instead of the new CodeDeploy Pipe.

**Comment by markiver** [comment]
Hello Alexander,

Thank you for taking the time to create this issue about Bitbucket's CodeDeploy application. The application you're referring to was created by Bitbucket and is not supported by AWS. AWS CodeDeploy's behavior with Bitbucket has not changed. CodeDeploy continues to support pushing code in a Bitbucket repository to your EC2 instances during a deployment.

I will pass on the fact that the referenced blog post should be updated so that it refers to the new Bitbucket application.

Kind regards,

Mark

**Comment by ZhukovAlexander** [comment]
Hi @markiver,

Not sure if I've phrased the issue correctly, but the actual problem is that this documentation is promoting a Bitbucket app that doesn't even exist anymore. 

> You can push code to Amazon EC2 instances directly from the Bitbucket UI to any of your deployment groups without having to sign in to your continuous integration (CI) platform or Amazon EC2 instances to run a manual deployment process

Bitbucket has removed this app from it's marketplace, and this app will stop working on 01 Jun 2020 and all users are expected to migrate to using the aws-code-deploy Bitbucket pipe.
