### ISSUE TITLE
Viewing Windows CodeDeploy logs in CloudWatch

### ISSUE THREAD

**Issue by philcart** [awsdocs/aws-codedeploy-user-guide#40]
While there are instructions for viewing the logs on the Windows instance, there isn't anything about viewing them on CloudWatch.

https://github.com/awsdocs/aws-codedeploy-user-guide/blob/master/doc_source/deployments-view-logs.md#view-log-file-data-in-the-amazon-cloudwatch-console

The linked blog post focuses on Linux hosts and I've not been able to find anything that provides guidence on how to achieve the same result for a Windows host.

**Comment by msuzoagu** [comment]
and now that link doesn't exist. AWS never fails to amuse (in horror)

**Comment by elijahbatkoski** [comment]
Sorry for the long delay here, @philcart. You have a valid point and I have an item on the backlog to try to address this but I can't give a time when it will be worked on right now.

@msuzoagu Sorry about the link issue, it's due to us changing our default branch from "master" to "main". The correct link is:  https://github.com/awsdocs/aws-codedeploy-user-guide/blob/main/doc_source/deployments-view-logs.md#view-log-file-data-in-the-amazon-cloudwatch-console

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
